import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Mic, Square, Loader2, ArrowRight } from 'lucide-react';
import { transcribeAudio, generateQuestion, detectContradiction } from '../../api';

interface InputFormProps {
    onSubmit: (text: string) => void;
    isLoading: boolean;
}

const MAX_QUESTIONS = 2;

export default function InputForm({ onSubmit, isLoading }: InputFormProps) {
    // -------------------------------------------------------------
    // Core State
    // -------------------------------------------------------------
    const [step, setStep] = useState(0); 
    // step 0: Initial prompt
    // step 1: Q1
    // step 2: Q2
    // step 3: Final confirmation -> submit

    const [qaHistory, setQaHistory] = useState<Array<{q: string, a: string}>>([]);
    const [currentAnswer, setCurrentAnswer] = useState('');
    const [currentQuestion, setCurrentQuestion] = useState('What goal or habit have you been trying to achieve, but keep failing at?');
    const [isThinking, setIsThinking] = useState(false);
    
    // Voice State
    const [isRecording, setIsRecording] = useState(false);
    const mediaRecorder = useRef<MediaRecorder | null>(null);
    const audioChunks = useRef<Blob[]>([]);

    // -------------------------------------------------------------
    // Step Definitions for the Left Pane
    // -------------------------------------------------------------
    const stepMeta = [
        { num: '01', title: 'The Synthesis', subtitle: 'Lay the groundwork.', caption: 'Tell us about the goal that has been actively resisting your efforts.' },
        { num: '02', title: 'Deep Dive', subtitle: 'Analyzing resistance.', caption: 'We need to unpack the friction points you mentioned.' },
        { num: '03', title: 'Pattern Extraction', subtitle: 'Finding the vector.', caption: 'Identifying the hidden psychology blocking your progress.' },
        { num: '04', title: 'Friction Analysis', subtitle: 'Contradiction check.', caption: 'Let\'s make sure we have the full picture before compiling the blueprint.' },
    ];

    const currentMeta = stepMeta[Math.min(step, stepMeta.length - 1)];

    // -------------------------------------------------------------
    // Handlers
    // -------------------------------------------------------------
    const handleNext = async () => {
        if (!currentAnswer.trim() || isThinking || isLoading) return;

        // If we are at the very last step (Step 3, 0-indexed), compile and submit
        if (step >= MAX_QUESTIONS + 1) {
            const finalHistory = [...qaHistory, { q: currentQuestion, a: currentAnswer }];
            let compiledNarrative = `Initial Context: ${finalHistory[0]?.a}\n`;
            for (let i = 1; i < finalHistory.length; i++) {
                compiledNarrative += `\nAgent Question: ${finalHistory[i].q}\nUser Answer: ${finalHistory[i].a}\n`;
            }
            onSubmit(compiledNarrative);
            return;
        }

        // Otherwise, move to next question generated by AI
        setIsThinking(true);
        try {
            const newHistory = [...qaHistory, { q: currentQuestion, a: currentAnswer }];
            let nextQ = "";

            // Construct history string from qaHistory
            const historyStr = newHistory.map(item => `Q: ${item.q}\nA: ${item.a}`).join('\n\n');
            const focus = newHistory[newHistory.length - 1].a;

            if (newHistory.length <= MAX_QUESTIONS) {
                nextQ = await generateQuestion(focus, historyStr);
            } else {
                const response = await detectContradiction(focus, historyStr);
                nextQ = response.tension_question || "Does anything feel off about this?";
            }

            setQaHistory(newHistory);
            setCurrentQuestion(nextQ);
            setCurrentAnswer('');
            setStep((s) => s + 1);
        } catch (error) {
            console.error("Agent failed to respond:", error);
            alert("Connection interrupted. Please try continuing.");
        } finally {
            setIsThinking(false);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleNext();
        }
    };

    // -------------------------------------------------------------
    // Voice Handling
    // -------------------------------------------------------------
    const startRecording = async () => {
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            mediaRecorder.current = new MediaRecorder(stream);
            audioChunks.current = [];

            mediaRecorder.current.ondataavailable = (event) => {
                audioChunks.current.push(event.data);
            };

            mediaRecorder.current.onstop = async () => {
                const audioBlob = new Blob(audioChunks.current, { type: 'audio/webm' });
                setIsThinking(true);
                try {
                    const data = await transcribeAudio(audioBlob);
                    setCurrentAnswer(data.raw_text);
                } catch (error) {
                    console.error("Transcription error:", error);
                    alert("Could not transcribe audio. Please try typing instead.");
                } finally {
                    setIsThinking(false);
                }
            };

            mediaRecorder.current.start();
            setIsRecording(true);
        } catch (error) {
            console.error("Microphone access denied:", error);
            alert("Could not access microphone.");
        }
    };

    const stopRecording = () => {
        if (mediaRecorder.current && isRecording) {
            mediaRecorder.current.stop();
            setIsRecording(false);
            mediaRecorder.current.stream.getTracks().forEach(track => track.stop());
        }
    };

    return (
        <div style={{
            display: 'flex',
            flexDirection: window.innerWidth < 768 ? 'column' : 'row',
            width: '100%',
            height: '100%',
            minHeight: '100vh',
            overflow: 'hidden',
            background: 'var(--bg-primary)'
        }}>
            
            {/* LEFT PANE - Dynamic Typography */}
            <div style={{
                flex: window.innerWidth < 768 ? 'none' : '0 0 40%',
                height: window.innerWidth < 768 ? '30vh' : 'auto',
                background: '#050505',
                borderRight: window.innerWidth < 768 ? 'none' : '1px solid rgba(255,255,255,0.05)',
                borderBottom: window.innerWidth < 768 ? '1px solid rgba(255,255,255,0.1)' : 'none',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                padding: '40px clamp(20px, 4vw, 60px)',
                position: 'relative',
                overflow: 'hidden'
            }}>
                {/* Decorative glowing orb */}
                <motion.div
                    animate={{
                        scale: [1, 1.2, 1],
                        opacity: [0.1, 0.15, 0.1],
                    }}
                    transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
                    style={{
                        position: 'absolute',
                        top: '30%',
                        left: '-20%',
                        width: '500px',
                        height: '500px',
                        background: 'radial-gradient(circle, var(--accent-glow) 0%, transparent 70%)',
                        filter: 'blur(60px)',
                        pointerEvents: 'none'
                    }}
                />

                <AnimatePresence mode="wait">
                    <motion.div
                        key={`meta-${step}`}
                        initial={{ opacity: 0, y: 40 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -40 }}
                        transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                        style={{ position: 'relative', zIndex: 1 }}
                    >
                        <div style={{ 
                            fontFamily: 'monospace', 
                            color: 'var(--text-accent)', 
                            fontSize: '1.2rem', 
                            letterSpacing: '4px',
                            marginBottom: '16px',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '12px'
                        }}>
                            <span style={{ width: '40px', height: '1px', background: 'var(--text-accent)' }} />
                            STEP {currentMeta.num}
                        </div>
                        
                        <h2 style={{ 
                            fontSize: 'clamp(3rem, 5vw, 4.5rem)', 
                            fontWeight: 300, 
                            lineHeight: 1.1,
                            color: 'var(--text-primary)',
                            marginBottom: '16px',
                            letterSpacing: '-1px'
                        }}>
                            {currentMeta.title}
                        </h2>
                        
                        <h3 style={{
                            fontSize: '1.5rem',
                            color: 'var(--text-secondary)',
                            fontWeight: 400,
                            marginBottom: '24px',
                            fontStyle: 'italic'
                        }}>
                            {currentMeta.subtitle}
                        </h3>

                        <p style={{
                            color: 'rgba(255,255,255,0.4)',
                            fontSize: '1rem',
                            lineHeight: 1.6,
                            maxWidth: '80%'
                        }}>
                            {currentMeta.caption}
                        </p>
                    </motion.div>
                </AnimatePresence>
            </div>

            {/* RIGHT PANE - Clean Input Area */}
            <div style={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                padding: window.innerWidth < 768 ? '40px 24px' : '40px clamp(40px, 6vw, 100px)',
                position: 'relative',
                background: 'radial-gradient(circle at 70% 30%, rgba(130, 202, 255, 0.03) 0%, transparent 50%)'
            }}>
                <AnimatePresence mode="wait">
                    <motion.div
                        key={`q-${step}`}
                        initial={{ opacity: 0, x: 40 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -40 }}
                        transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
                        style={{ width: '100%', maxWidth: '800px' }}
                    >
                        {/* Question */}
                        <div style={{
                            fontSize: '2rem',
                            fontWeight: 500,
                            lineHeight: 1.4,
                            color: 'var(--text-primary)',
                            marginBottom: '40px'
                        }}>
                            {currentQuestion}
                        </div>

                        {/* Input Core */}
                        <div style={{ position: 'relative' }}>
                            <textarea
                                value={currentAnswer}
                                onChange={(e) => setCurrentAnswer(e.target.value)}
                                onKeyDown={handleKeyDown}
                                disabled={isThinking || isLoading || isRecording}
                                placeholder="Type your response or use voice..."
                                style={{
                                    width: '100%',
                                    minHeight: '200px',
                                    background: 'transparent',
                                    border: 'none',
                                    borderBottom: '2px solid rgba(255,255,255,0.1)',
                                    color: 'var(--text-primary)',
                                    fontSize: '1.25rem',
                                    lineHeight: 1.6,
                                    padding: '24px 0',
                                    resize: 'none',
                                    outline: 'none',
                                    transition: 'border-color 0.3s'
                                }}
                                onFocus={(e) => e.target.style.borderBottomColor = 'var(--text-accent)'}
                                onBlur={(e) => e.target.style.borderBottomColor = 'rgba(255,255,255,0.1)'}
                            />

                            {/* Toolbar under textarea */}
                            <div style={{
                                display: 'flex',
                                justifyContent: 'space-between',
                                alignItems: 'center',
                                marginTop: '24px'
                            }}>
                                {/* Voice Capture */}
                                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                                    <button
                                        type="button"
                                        onClick={isRecording ? stopRecording : startRecording}
                                        disabled={isThinking || isLoading}
                                        style={{
                                            background: isRecording ? 'rgba(255, 123, 123, 0.1)' : 'rgba(255,255,255,0.03)',
                                            border: `1px solid ${isRecording ? '#ff7b7b' : 'rgba(255,255,255,0.1)'}`,
                                            color: isRecording ? '#ff7b7b' : 'var(--text-secondary)',
                                            width: '50px',
                                            height: '50px',
                                            borderRadius: '50%',
                                            display: 'flex',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                            cursor: (isThinking || isLoading) ? 'not-allowed' : 'pointer',
                                            transition: 'all 0.3s ease'
                                        }}
                                    >
                                        {isRecording ? <Square size={20} fill="currentColor" /> : <Mic size={20} />}
                                    </button>
                                    
                                    {isRecording && (
                                        <motion.div
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            style={{ color: '#ff7b7b', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '8px' }}
                                        >
                                            <div className="pulse-dot" style={{ width: '8px', height: '8px', background: '#ff7b7b', borderRadius: '50%', animation: 'pulse 1.5s infinite' }} />
                                            Listening...
                                        </motion.div>
                                    )}
                                </div>

                                {/* Next Button */}
                                <button
                                    onClick={handleNext}
                                    disabled={!currentAnswer.trim() || isThinking || isLoading || isRecording}
                                    style={{
                                        background: (!currentAnswer.trim() || isThinking || isLoading) ? 'rgba(255,255,255,0.05)' : 'var(--text-primary)',
                                        color: (!currentAnswer.trim() || isThinking || isLoading) ? 'var(--text-muted)' : 'var(--bg-primary)',
                                        border: 'none',
                                        padding: '16px 32px',
                                        borderRadius: '30px',
                                        fontSize: '1rem',
                                        fontWeight: 600,
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '12px',
                                        cursor: (!currentAnswer.trim() || isThinking || isLoading) ? 'not-allowed' : 'pointer',
                                        transition: 'all 0.3s ease'
                                    }}
                                >
                                    {(isThinking || isLoading) ? (
                                        <>Processing <Loader2 size={18} className="spinner" /></>
                                    ) : (
                                        <>{step >= MAX_QUESTIONS + 1 ? 'Synthesize Plan' : 'Continue'} <ArrowRight size={18} /></>
                                    )}
                                </button>
                            </div>
                        </div>
                    </motion.div>
                </AnimatePresence>
            </div>
            
            <style>{`
                @keyframes pulse {
                    0% { transform: scale(0.95); opacity: 0.5; }
                    50% { transform: scale(1.2); opacity: 1; }
                    100% { transform: scale(0.95); opacity: 0.5; }
                }
            `}</style>
        </div>
    );
}
