import PageShell from '../components/site/PageShell';
import { PageHero } from '../components/site/ui';
import { useWindowSize } from '../hooks/useWindowSize';
import LegalDoc, { type LegalSection } from '../components/legal/LegalDoc';

/**
 * The published Terms of Service.
 *
 * Text finalised with counsel's draft of 3 August 2026, corrected against the
 * application as built (see the alignment brief of 19 September 2026):
 * registration takes an email and password (or Google sign-in) with an
 * optional name; crisis language pauses coaching for that message rather
 * than locking the app; the "not a health service" acknowledgement is part
 * of the sign-up consent; the AI providers match the Privacy Policy.
 *
 * TERMS_VERSION follows the Privacy Policy's version scheme (the date of the
 * last material change).
 */
const TERMS_VERSION = '2026-09-28';
const LAST_UPDATED = '28 September 2026';

const HELPLINES: string[][] = [
  ['UK', 'Samaritans (24/7)', '116 123 (free)'],
  ['UK', 'SHOUT (24/7 text line)', 'Text SHOUT to 85258'],
  ['UK', 'NHS 111 (mental health option)', '111'],
  ['UK', 'CALM (5pm–midnight)', '0800 58 58 58'],
  ['Europe', 'Emotional support helpline', '116 123'],
  ['EU', 'Emergency services', '112'],
  ['India', 'Tele-MANAS (24/7)', '14416 or 1-800-891-4416'],
  ['US', '988 Suicide & Crisis Lifeline', '988'],
  ['US', 'Emergency services', '911'],
  ['Anywhere', 'Find a verified helpline', '[findahelpline.com](https://findahelpline.com)'],
];

const SECTIONS: LegalSection[] = [
  { id: 'agreement', h: 'This agreement', blocks: [
    { t: 'p', text: 'By (i) accessing our site, (ii) creating an account, or (iii) using our services, you acknowledge and accept these Terms of Service, as updated from time to time ("Terms"). If you disagree, you may opt not to use our site.' },
    { t: 'p', text: 'This agreement constitutes an electronic record under the laws and regulations governing electronic records in the United Kingdom and the European Union. It is produced by a computer system and does not require a physical or digital signature.' },
    { t: 'p', text: 'In these Terms, "we", "our" and "us" refer to JUNE64 Ltd, a private limited company incorporated under the Companies Act 2006 (company number 16436481) with its registered office at 124–128 City Road, London, England ("Feelivate"), the provider of Feelivate. "You", "your" and "user" refer to the natural person who uses our Services and is legally capable of entering into a binding contract.' },
    { t: 'p', text: 'These Terms and our [Privacy Policy](https://feelivate.com/privacy) form a legally binding agreement between you and Feelivate.' },
  ] },

  { id: 'who-can-use', h: 'Who can use Feelivate', blocks: [
    { t: 'p', text: 'You must be 18 or older. We ask you to confirm this when you sign up. If we learn that an account belongs to someone under 18, we will close it and delete the data.' },
    { t: 'p', text: 'To register, provide an email address and a password, or sign in with your Google account. You may optionally add your name. When registering, ensure your information is accurate, current and complete.' },
    { t: 'p', text: 'You are responsible for keeping your login details secure and for what happens under your account. You agree not to sell, transfer or assign your account, to keep your account details private, and to report any unauthorised use to us immediately.' },
  ] },

  { id: 'what-is-feelivate', h: 'What is Feelivate?', blocks: [
    { t: 'p', text: 'Feelivate is an AI accountability mentor. You describe a goal, it builds a specific 7-day plan, and it holds you to it with daily emails, check-ins, streaks and weekly reports. You can also record voice notes and log how you are feeling, and the mentor adapts the next week accordingly (the "Service" or "Services").' },
    { t: 'p', text: 'You are talking to an AI system, not a human. Every response in the app is generated by a large language model. If you ask it whether it is an AI, it will tell you the truth.' },
    { t: 'p', text: 'We may add, change or remove features. If a change materially reduces what you get, we will tell you in advance.' },
  ] },

  { id: 'not-a-health-service', h: 'Feelivate is NOT a health service', blocks: [
    { t: 'note', text: '**Important notice.** Please review this section carefully. By creating an account you confirm that you have read and understood it, and that you understand Feelivate is not a health or crisis service.' },
    { t: 'h3', text: 'What Feelivate cannot do for you' },
    { t: 'p', text: 'Feelivate is not a medical, psychological, psychiatric, therapeutic or mental-health service. It is not a medical device as defined under the Medical Devices Regulation (EU) 2017/745, the UK Medical Devices Regulations 2002, or any equivalent legislation.' },
    { t: 'p', text: 'It does not:' },
    { t: 'ul', items: [
      'diagnose, treat, cure, prevent or monitor any physical or mental health condition;',
      'provide clinical assessments or medical opinions;',
      'replace the judgment of a qualified healthcare professional.',
    ] },
    { t: 'p', text: 'The "Emotion Score" and associated labels are a rough, non-clinical interpretation generated by our AI based on what you write; not a validated psychological or medical measurement; and not a diagnosis, screening tool or indicator of any health condition. You should not rely on the emotion score for any health-related decision.' },
    { t: 'h3', text: 'No professional advice' },
    { t: 'p', text: 'Nothing in the app, including AI-generated plans, reports, suggestions or any other content, constitutes medical, psychological or professional advice of any kind. Always speak to a qualified doctor, therapist or licensed professional about any physical or mental health concern. If you are unsure whether you need professional help, seek it.' },
    { t: 'h3', text: 'Your responsibility' },
    { t: 'p', text: 'By using Feelivate, you acknowledge and agree that you are solely responsible for your own health and wellbeing decisions; you will not use Feelivate as a substitute for professional medical or mental-health care; you will seek appropriate professional help when needed; and any action you take based on AI-generated content is at your own risk.' },
    { t: 'h3', text: 'Feelivate is not built for emergencies and cannot help you in one' },
    { t: 'p', text: 'The app does not provide crisis counselling or intervention, monitor your safety in real time, connect you to emergency services, or offer any form of urgent support. If you are in crisis, do not use the app. Call real help immediately.' },
    { t: 'table', head: ['Region', 'Service', 'Contact'], rows: HELPLINES },
    { t: 'p', text: 'If you are thinking about harming yourself or ending your life, please contact real help now. If you are in immediate danger, call your local emergency number now. Do not wait.' },
    { t: 'h3', text: 'What the app does if it detects risk' },
    { t: 'p', text: 'Our AI may detect language in your chat messages, journal entries or voice transcripts that suggests you may be at risk of harm to yourself or others. If this happens, the app will pause coaching for that message, show you the crisis resources listed above, and encourage you to contact a real person who can help. You can continue using the app afterwards; nothing is recorded against you.' },
    { t: 'p', text: 'This is a signpost, not a safety net. It is not a substitute for speaking to a qualified professional, not a safeguard or guarantee of your safety, and not a replacement for emergency services. You should never rely on the app to detect or respond to a crisis. The AI may miss signs, misinterpret what you write, or fail to respond appropriately. If you are in crisis, do not use the app – call real help immediately.' },
  ] },

  { id: 'ai-limits', h: 'What the AI can and cannot do', blocks: [
    { t: 'p', text: 'AI-generated responses are not always accurate, complete or reliable; may be confidently wrong, or occasionally produce inappropriate content; and should be judged with your own common sense before you act on them.' },
    { t: 'p', text: 'Do not rely on Feelivate for anything where being wrong would cause you harm.' },
  ] },

  { id: 'lock-in', h: 'The "Lock-In Protocol"', blocks: [
    { t: 'p', text: 'When you approve a week, the plan locks. You cannot quietly soften it mid-week to make it easier. That is a deliberate commitment device, and it is the core of how the product works.' },
    { t: 'p', text: 'To be clear about what locking is not: it is a rule inside the app, not an obligation you owe us. You can end an ongoing session or a plan at any time using the "Stop" (finish this goal) action, and start a new one. Nothing is charged, forfeited or penalised if you stop. Streaks and reports are motivational features, nothing more.' },
  ] },

  { id: 'your-content', h: 'Your content', blocks: [
    { t: 'p', text: 'Your goals, plans, journal entries, voice transcripts, notes and all other content you create ("Your Content") remain yours. We claim no ownership of it.' },
    { t: 'p', text: 'To provide Feelivate to you, you grant us a limited, non-exclusive, royalty-free licence to store, process (including sending to our AI providers as described in our Privacy Policy) and display Your Content back to you. This licence ends when you delete your account.' },
    { t: 'p', text: 'We do not publish, sell or use Your Content for advertising.' },
    { t: 'p', text: 'You can download everything at any time from Profile → Download my data as a machine-readable JSON file, free of charge. This remains available if we ever terminate or change the service.' },
    { t: 'h3', text: 'Our intellectual property' },
    { t: 'p', text: 'All rights to the Feelivate platform, software, prompts, trademarks and underlying technology remain ours. You may use the service only for your personal, non-commercial purposes. You may not copy, modify, reverse-engineer or resell any part of it.' },
    { t: 'h3', text: 'AI provider processing' },
    { t: 'p', text: 'Your Content is processed by our AI providers – currently OpenRouter, Inc. and the model hosts it routes to, Groq, Inc. and OpenAI, L.L.C. – as described in our [Privacy Policy](https://feelivate.com/privacy#ai-processing). Their API terms prohibit the use of your data to train their models; we are in the process of putting formal contractual arrangements in place to the same effect.' },
    { t: 'h3', text: 'Feedback' },
    { t: 'p', text: 'Any feedback or suggestions you provide may be used by us without compensation to you.' },
  ] },

  { id: 'acceptable-use', h: 'How you agree to use it', blocks: [
    { t: 'p', text: 'You agree to use Feelivate responsibly and lawfully. You must not:' },
    { t: 'ul', items: [
      'break any law or use the service to harm or harass anyone;',
      'attempt to break, overload, reverse-engineer or gain unauthorised access to the service;',
      'resell, redistribute, sublicense or scrape the service in bulk;',
      'upload anyone else\'s personal information without their explicit consent;',
      'upload unlawful, defamatory, abusive or infringing content;',
      'create multiple accounts or use another person\'s account without permission.',
    ] },
    { t: 'p', text: 'You are responsible for all activity under your account. If you suspect unauthorised use, notify us immediately.' },
    { t: 'p', text: 'By using our Services, you agree to follow all rules, guidelines and policies. No signature is needed; use of the service means you accept these Terms.' },
  ] },

  { id: 'price', h: 'Price', blocks: [
    { t: 'p', text: 'Feelivate is currently free. There is no charge and no card on file.' },
    { t: 'p', text: 'If we introduce paid plans, we will tell you beforehand and you will never be charged without agreeing to it first. When we do:' },
    { t: 'ul', items: [
      'prices will be shown inclusive of applicable taxes;',
      'as an EU or EEA consumer you will have a 14-day right of withdrawal from the date of purchase under the Consumer Rights Directive, unless you ask us to start the service immediately and acknowledge losing that right;',
      'you will be able to cancel a subscription at any time.',
    ] },
  ] },

  { id: 'our-responsibilities', h: 'Our responsibilities to you', blocks: [
    { t: 'p', text: 'We will provide Feelivate with reasonable care and skill as required by law.' },
    { t: 'p', text: 'If you are a consumer in the EU or EEA, you have statutory rights we cannot sign away – including, under the Digital Content Directive (EU) 2019/770, the right to a service that conforms to what we described, and to a remedy if it does not. Those rights apply even though Feelivate is free, because the law treats a service supplied in exchange for personal data the same way. Nothing in these Terms limits them.' },
    { t: 'p', text: 'Outside those statutory rights, the service is provided as it is, to the extent permitted by law. We cannot promise it will always be available, uninterrupted or error-free, or that the AI\'s output will meet your expectations.' },
  ] },

  { id: 'indemnification', h: 'Indemnification', blocks: [
    { t: 'p', text: 'You agree to indemnify, defend and hold harmless Feelivate, our affiliates, and our directors, officers, employees and agents (collectively, the "Parties") from any losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and interest) arising from your wilful misuse of the service in violation of applicable law; your fraudulent activity; or your breach of these Terms that causes harm to us or third parties.' },
    { t: 'p', text: 'This indemnity does not apply to the extent that the claim arises from our own negligence or breach of these Terms.' },
    { t: 'p', text: 'You agree to cooperate fully in indemnifying us at your expense and not to settle any claim without our consent.' },
    { t: 'p', text: 'Under no circumstances shall we be liable for any special, incidental, indirect, consequential or punitive damages, including loss of use, data or profits, arising from your use of our Services, whether or not such damages were foreseeable, we were advised of the possibility of such damages, or based on any theory of liability.' },
  ] },

  { id: 'liability', h: 'Limits on liability', blocks: [
    { t: 'note', text: '**You use Feelivate at your own risk.** To the fullest extent permitted by law, we exclude all liability for any loss, damage, injury, cost or expense of any kind arising from your use of Feelivate or your inability to use it; from anything it produces – plans, tasks, reports, emotion scores, guides, emails and chat replies; from your reliance on any of it; or from anything you do or do not do as a result. Feelivate is a free motivational tool, and you accept it on that basis.' },
    { t: 'p', text: 'The law does not allow us to exclude everything, and we do not try to. Nothing in these Terms limits or excludes our liability for fraud or fraudulent misrepresentation; for death or personal injury caused by our negligence; for breach of terms implied by the Consumer Rights Act 2015 (UK) or the Digital Content Directive (EU) 2019/770; for other statutory liabilities including breach of data protection laws; or for any liability which cannot be limited or excluded under the law of your country. Where the law does not allow an exclusion, our liability is limited to the fullest extent it does allow.' },
    { t: 'p', text: 'Subject to the above, and to the fullest extent permitted by law:' },
    { t: 'ul', items: [
      'We provide Feelivate "as is" and "as available", without warranties of any kind, for users outside the EU, EEA and UK. For EU, EEA and UK consumers, we provide it with reasonable care and skill and nothing more is promised.',
      'We are not liable for any loss or damage that was not reasonably foreseeable by both parties; any indirect or consequential loss, including loss of profits, business, goodwill, opportunity or data; any loss arising from your acts or omissions, including inaccurate information, decisions you take, or failure to secure your account; or interruptions, errors or data loss caused by factors outside our control, including connectivity issues, our hosting and AI providers, or other third-party failures.',
      'To the extent the law allows, our total liability to you for all claims in any 12-month period is limited to the greater of the amount you paid us in that period (if any) or €250.',
      'We are not liable for any third-party services you connect to Feelivate, or for the acts or omissions of our AI providers.',
      'You remain responsible for the decisions you make about your own health, finances, work and life, whatever the app suggests.',
    ] },
    { t: 'h3', text: 'No duty of care' },
    { t: 'p', text: 'To the fullest extent permitted by law, Feelivate assumes no duty of care to you or any third party regarding your health, safety or wellbeing; is not responsible for monitoring your mental or physical health; and is not liable for any failure to detect, respond to or prevent any harm or crisis. You remain fully responsible for your own safety and wellbeing at all times.' },
  ] },

  { id: 'no-warranties', h: 'AI-generated content – no warranties', blocks: [
    { t: 'ul', items: [
      'The AI outputs in Feelivate (including plans, tasks, reports, guides and suggestions) are for informational and motivational purposes only.',
      'They are not guaranteed to be accurate, complete, reliable or effective for your circumstances.',
      'They are not a substitute for professional advice of any kind.',
      'You use AI-generated content at your own risk and should exercise your own judgment before acting on it.',
    ] },
  ] },

  { id: 'changes', h: 'Changing these Terms', blocks: [
    { t: 'p', text: 'We may update these Terms. If a change is material, we will give you at least 30 days\' notice by email or in the app; tell you plainly what is changing; and let you reject it by closing your account before it takes effect, with your data exportable up to that point.' },
    { t: 'p', text: 'We will not treat continued use as agreement to a material change without giving you that notice and that choice first.' },
  ] },

  { id: 'termination', h: 'Termination', blocks: [
    { t: 'p', text: 'You can stop at any time. Deleting your account from the profile menu ends these Terms immediately and erases your data (see the Privacy Policy).' },
    { t: 'p', text: 'We may suspend or terminate your account if you seriously or repeatedly breach these Terms, or if we are legally required to. Except where the law or the seriousness of the breach makes it impossible, we will tell you why first and give you a chance to put it right. You will be able to export your data before termination.' },
    { t: 'p', text: 'Termination does not limit our right to take any other action against you that is appropriate to protect the integrity and security of our Services. Provisions that by their nature should survive termination (including those on your content, liability and governing law) survive it.' },
  ] },

  { id: 'governing-law', h: 'Governing law and where disputes go', blocks: [
    { t: 'p', text: 'These Terms are governed by the laws of England and Wales, and the courts of London, England have exclusive jurisdiction, subject to the following.' },
    { t: 'p', text: '**If you are a consumer in the EU or EEA:** you retain the protection of the mandatory consumer laws of the country where you live, and you may bring proceedings against us in the courts of your country. We may only sue you in the courts of your country. EU/EEA consumers may also use the online dispute resolution platform at [ec.europa.eu/consumers/odr](https://ec.europa.eu/consumers/odr).' },
    { t: 'p', text: '**If you are a consumer resident in the United Kingdom:** these Terms are governed by English law and the courts of England and Wales have jurisdiction over any disputes. Nothing in this clause affects your rights under the Consumer Rights Act 2015 or any other mandatory UK consumer protection legislation.' },
  ] },

  { id: 'other-terms', h: 'Other terms', blocks: [
    { t: 'ul', items: [
      'If any provision of these Terms is found to be invalid, illegal or unenforceable by a court of competent jurisdiction, the remaining provisions remain valid and enforceable to the fullest extent permitted by law. The invalid provision shall be reformed to the extent necessary to uphold the original intent of these Terms.',
      'Our failure to enforce any provision of these Terms, or to exercise any right under them, at any time does not waive that provision or right, or our right to enforce any subsequent breach.',
      'These Terms, together with the [Privacy Policy](https://feelivate.com/privacy), are the whole agreement between us about Feelivate.',
    ] },
  ] },

  { id: 'contact', h: 'Contact', blocks: [
    { t: 'p', text: 'If you have any questions regarding these Terms, the practices of our Services, or your experience, please contact us:' },
    { t: 'table', head: ['', ''], rows: [
      ['Support', '[info@june64.com](mailto:info@june64.com)'],
      ['Company', 'JUNE64 Ltd, 124–128 City Road, London, England (company number 16436481)'],
    ] },
    { t: 'p', text: 'Our representatives are authorised to receive communications on our behalf regarding data protection matters. You may contact them in your own language.' },
  ] },
];

export default function TermsPage() {
  const { isMobile } = useWindowSize();
  return (
    <PageShell
      seo={{
        title: 'Terms of Service | Feelivate',
        description: 'The terms that govern your use of Feelivate, the AI accountability mentor by JUNE64.',
        path: '/terms',
      }}
    >
      <PageHero kicker="Legal" title="Terms of Service" subtitle="The rules for using Feelivate." isMobile={isMobile} />
      <LegalDoc lastUpdated={LAST_UPDATED} version={TERMS_VERSION} sections={SECTIONS} />
    </PageShell>
  );
}
