import PageShell from '../components/site/PageShell';
import { PageHero, clash, satoshi } from '../components/site/ui';
import { useWindowSize } from '../hooks/useWindowSize';

/**
 * The published terms.
 *
 * Kept in sync with `terms-and-conditions.md`, which lives in the parent
 * project folder alongside the compliance pack and is deliberately not tracked
 * in this repo. That file is the source of truth. Two published versions that
 * disagree is worse than one imperfect one.
 *
 * TODO before EU launch:
 *   1. Registered legal name and address of the contracting entity
 *   2. Governing law / jurisdiction, and the liability floor amount
 *   3. Have the whole thing reviewed by an EU-qualified lawyer
 */
const TERMS_VERSION = '2026-07-29';
const LAST_UPDATED = '29 July 2026';

const SECTIONS: { h: string; p: string[] }[] = [
  { h: 'Acceptance and eligibility', p: [
    'These Terms are an agreement between you and JUNE64, the provider of Feelivate. By creating an account you agree to them.',
    'You must be 18 or older to use Feelivate, and we ask you to confirm this when you sign up. If we learn that an account belongs to someone under 18, we will close it and delete the data.',
    'Where a clause here would be unfair or unenforceable against a consumer under the law of your country, it simply does not apply to you — the rest of the Terms stay in force.',
  ] },

  { h: 'What Feelivate is', p: [
    'Feelivate is an AI accountability mentor. You describe a goal, it builds a specific 7-day plan, and it keeps you to it with daily emails, check-ins, streaks and weekly reports. You can also record voice notes and log how you are feeling, and the mentor adapts the next week accordingly.',
    'You are talking to an AI system, not a human. Every response in the app is generated by a large language model, and it will tell you so if you ask.',
    'We may add, change or remove features. If a change materially reduces what you get, we will tell you in advance.',
  ] },

  { h: 'Feelivate is not a health service', p: [
    'Feelivate is not a medical, psychological, psychiatric, therapeutic or mental-health service, and it is not a medical device. It does not diagnose, treat, cure, prevent or monitor any condition.',
    'The emotion score is a rough label our AI attaches to what you wrote. It is not a clinical measure and means nothing medically.',
    'Nothing in the app is medical or professional advice. Always speak to a qualified doctor or licensed professional about any physical or mental health concern.',
  ] },

  { h: 'If you are in crisis', p: [
    'Feelivate is not built for emergencies and cannot help you in one. If you are thinking about harming yourself or ending your life, please contact real help now.',
    'Emergency services: 112 in the EU and India, 911 in the US, or your local emergency number.',
    'Europe: 116 123, the emotional support helpline available in many European countries. India: Tele-MANAS on 14416 or 1-800-891-4416, free and 24/7. Anywhere: findahelpline.com lists verified helplines for almost every country.',
    'If you write something that suggests you may be at risk, the app will stop coaching and show you these resources. That is a signpost, not a safety net.',
  ] },

  { h: 'What the AI can and cannot do', p: [
    'AI-generated responses are not always accurate, complete or reliable. The model may be confidently wrong, or occasionally produce inappropriate content.',
    'Judge what it tells you with your own common sense before acting on it. Do not rely on Feelivate for anything where being wrong would cause you harm.',
  ] },

  { h: 'The Lock-In Protocol', p: [
    'When you approve a week, the plan locks — you cannot quietly soften it mid-week to make it easier. That is a deliberate commitment device and it is the core of how the product works.',
    'To be clear about what locking is not: it is a rule inside the app, not an obligation you owe us. You can stop or abandon a plan at any time, start a new one, or delete your account outright. Nothing is charged, forfeited or penalised if you stop. Streaks and reports are motivational features, nothing more.',
  ] },

  { h: 'Your content', p: [
    'Your goals, plans, journal entries, voice notes, transcripts and notes remain yours. We claim no ownership of them.',
    'You grant us only the permission we need to run the service for you: to store your content, process it (including sending it to our AI providers as described in the Privacy Policy), and show it back to you. We do not publish your content, sell it, or use it to advertise to you.',
    'You can download everything at any time from your profile menu, as a machine-readable file, free of charge. This remains available to you if we ever terminate or change the service.',
  ] },

  { h: 'Acceptable use', p: [
    'Do not break the law with Feelivate, or use it to harm or harass anyone.',
    'Do not try to break, overload, reverse-engineer or gain unauthorised access to the service, resell or redistribute it, or scrape it in bulk.',
    'Do not upload someone else’s personal information without their knowledge.',
    'You are responsible for keeping your login details secure and for what happens under your account.',
  ] },

  { h: 'Price', p: [
    'Feelivate is currently free. There is no charge and no card on file.',
    'If we introduce paid plans we will tell you beforehand, and you will never be charged without agreeing first. Prices will be shown inclusive of applicable taxes and you will be able to cancel at any time.',
    'As an EU or EEA consumer you will have a 14-day right of withdrawal from the date of purchase under the Consumer Rights Directive, unless you ask us to start the service immediately and acknowledge losing that right.',
  ] },

  { h: 'Our responsibilities to you', p: [
    'We will provide Feelivate with reasonable care and skill.',
    'If you are a consumer in the EU or EEA, you have statutory rights we cannot sign away — including, under the Digital Content Directive (EU) 2019/770, the right to a service that conforms to what we described and to a remedy if it does not. Those rights apply even though Feelivate is free, because the law treats a service supplied in exchange for personal data the same way. Nothing in these Terms limits them.',
    'Outside those statutory rights, the service is provided as it is: we cannot promise it will always be available, uninterrupted or error-free, or that the AI’s output will meet your expectations.',
  ] },

  { h: 'Limits on liability', p: [
    'We are fully liable for death or personal injury caused by our negligence, for fraud or fraudulent misrepresentation, for gross negligence or wilful misconduct, and for anything else that cannot be limited under the law that applies to you.',
    'Subject to that, and to the extent the law allows, we are not liable for indirect or consequential loss or loss of profits, and our total liability in any 12-month period is capped as set out in our full Terms.',
    'You remain responsible for the decisions you make about your own health, finances, work and life, whatever the app suggests.',
  ] },

  { h: 'Changing these terms', p: [
    'We may update these Terms. If a change is material we will give you at least 30 days’ notice by email or in the app, tell you plainly what is changing, and let you reject it by closing your account before it takes effect — with your data exportable up to that point.',
    'We will not treat continued use as agreement to a material change without giving you that notice and that choice first.',
  ] },

  { h: 'Ending the agreement', p: [
    'You can stop at any time. Deleting your account from the profile menu ends these Terms immediately and erases your data.',
    'We may suspend or close your account if you seriously or repeatedly breach these Terms, or if we are legally required to. Except where the law or the seriousness of the breach makes it impossible, we will tell you why first, give you a chance to put it right, and let you export your data.',
  ] },

  { h: 'Governing law and disputes', p: [
    'These Terms are governed by the law of the jurisdiction stated in our full Terms, whose courts have jurisdiction.',
    'If you are a consumer resident in the EU or EEA, that takes nothing away from you: you keep the protection of the mandatory consumer law of the country you live in (Rome I Regulation, Article 6), you may bring proceedings against us in the courts of your own country, and we may only sue you in yours (Brussels Ia Regulation, Articles 17–19).',
    'You can also use the European Commission’s online dispute resolution platform at ec.europa.eu/consumers/odr.',
  ] },

  { h: 'Contact', p: [
    'Questions about these Terms: info@june64.com. Feelivate is a product of JUNE64.',
  ] },
];

export default function TermsPage() {
  const { isMobile } = useWindowSize();
  return (
    <PageShell
      seo={{
        title: 'Terms of Service | Feelivate',
        description: 'The terms that govern your use of Feelivate, the AI accountability mentor by JUNE64.',
        path: '/terms',
      }}
    >
      <PageHero kicker="Legal" title="Terms of Service" subtitle="The rules for using Feelivate." isMobile={isMobile} />
      <section style={{ padding: isMobile ? '40px 20px 80px' : '56px 48px 100px' }}>
        <div style={{ maxWidth: '760px', margin: '0 auto' }}>
          <p
            style={{
              fontSize: '13px',
              color: 'var(--text-muted)',
              fontFamily: satoshi,
              fontWeight: 600,
              letterSpacing: '0.04em',
              marginBottom: '8px',
            }}
          >
            Last updated {LAST_UPDATED} · Version {TERMS_VERSION}
          </p>

          {SECTIONS.map((s, i) => (
            <div key={s.h} style={{ paddingTop: '24px', paddingBottom: '24px', borderTop: i === 0 ? 'none' : '1px solid var(--border-subtle)' }}>
              <h2 style={{ fontSize: isMobile ? '19px' : '22px', fontWeight: 700, fontFamily: clash, letterSpacing: '-0.02em', marginBottom: '12px' }}>{s.h}</h2>
              {s.p.map((para) => (
                <p key={para} style={{ fontSize: '14.5px', color: 'var(--text-secondary)', lineHeight: 1.7, fontFamily: satoshi, fontWeight: 500, marginBottom: '10px' }}>{para}</p>
              ))}
            </div>
          ))}
        </div>
      </section>
    </PageShell>
  );
}
